<!DOCTYPE html>
<html>
<head>
	<title>EJERCICIO JESUATH ALMARIO</title>
</head>
<H1>BANCO BBVA</H1>

<body>
    <form action="RECIBIDO.PHP" method="POST" >
    CODIGO: <input type="text" name="CODIGO" />
    <br></br>
    CAPITAL: <input type="text" name="CAPITAL" />
    <br></br> 
    DIA DEL CALENDARIO: <input type="text" name="DIA" />
    <br></br>
    TASA DE INTERES: <input type="text" name="TASA" /> 
    <br></br> 
        <input type="submit" value="enviar">
    </form>
</body>
</html>